name: Test Build

on: push

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run Pre-Commit
        uses: pre-commit/action@v2.0.3

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Set up Go 1.20.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Binary
        run: go build -v .

      - name: Test Listen Command
        shell: 'script -q -e -c "bash {0}"'
        run: ./checkup listen -e https://google.com

      - name: Test Exam Command Yaml
        shell: 'script -q -e -c "bash {0}"'
        run: ./checkup exam -f test.yml

      - name: Test Exam Command Json
        shell: 'script -q -e -c "bash {0}"'
        run: ./checkup exam -f test.json
