name: Test Build

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Binary
      run: go build -v .

    - name: Test Listen Command
      run: ./checkup listen -e https://google.com

    - name: Test Exam Command Yaml
      run: ./checkup exam -f test.yml

    - name: Test Exam Command Json
      run: ./checkup exam -f test.yml